# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#"
  weight = 10

# da finire
# [[main]]
#   name = "Gallery"
#   url = "/gallery"
#   weight = 15

[[main]]
  name = "Colore"
  url = "#colore"
  weight = 20

[[main]]
  name = "Parole"
  url = "#parole"
  weight = 30

[[main]]
  name = "Full bio"
  url = "#fullbio"
  weight = 40

[[main]]
  name = "Contatti"
  url = "#contatti"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
